Модуль 2 Задача 1
js-tasks-ru/js-20201030_face-void pull request #2
Opened 2020-11-06 07:07 UTC by facevoid63

2020-11-06 07:15 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
sortStrings
+ should return sorted by "asc" array of strings
+ should return a new sorted array
+ should return sorted by "desc" array of strings in "en" locale
+ should correctly sort language-specific characters in "ru" locale
+ should correctly sort strings started from uppercase
+ should correctly sort strings for mixed "en" and "ru" locales
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2020-11-06 14:44 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    newAr.reverse();
операция `reverse` здесь лишняя. Попробуйте избавиться от нее.
Массив следует сразу сортировать в заданном порядке

2020-11-06 14:44 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2020-11-06 17:25 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-11-08 20:04 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
sortStrings
+ should return sorted by "asc" array of strings
+ should return a new sorted array
+ should return sorted by "desc" array of strings in "en" locale
+ should correctly sort language-specific characters in "ru" locale
+ should correctly sort strings started from uppercase
+ should correctly sort strings for mixed "en" and "ru" locales
```
```diff
createGetter
+ should return existed properties
+ should return "undefined" for properties which does not exist
+ gets obj.property
+ returns undefined for no property
+ gets obj.nested.property
+ returns undefined for no nested.property
+ gets more.nested.property
```
```diff
pick
+ should return new object with one passed field
+ should return new object with a few passed field
+ should return an empty object if passed fields does not found
```
```diff
trimSymbols
+ should remove an identical consecutive characters that exceed the specified size
+ should return empty string if it was passed to function like an argument
+ should return empty string if "size" equal 0
+ should return the same string if "size" parameter wasn't specified
```
```diff
invertObj
+ should swap keys and values and return new object
+ should return empty object if was passed object without values
+ should return "undefined" if object wasn't passed
```
```diff
omit
+ should return a new object without passed field
+ should return a new object without few passed fields
+ should return initial object if passed fields doesn't found
```
```diff
uniq
- should return array with uniq values
- should return empty array if was passed array without values
- should return empty array if arguments wasn't passed
```

2020-11-09 06:55 UTC, closed without merging

2020-11-09 06:55 UTC, facevoid63 commented
Открою новый pr с решениями дальнейших задач