Исправления в задаче 2го модуля, решения 3го модуля
js-tasks-ru/js-20201030_face-void pull request #3
Opened 2020-11-09 06:57 UTC by facevoid63

2020-11-09 07:04 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
sortStrings
+ should return sorted by "asc" array of strings
+ should return a new sorted array
+ should return sorted by "desc" array of strings in "en" locale
+ should correctly sort language-specific characters in "ru" locale
+ should correctly sort strings started from uppercase
+ should correctly sort strings for mixed "en" and "ru" locales
```
```diff
createGetter
+ should return existed properties
+ should return "undefined" for properties which does not exist
+ gets obj.property
+ returns undefined for no property
+ gets obj.nested.property
+ returns undefined for no nested.property
+ gets more.nested.property
```
```diff
pick
+ should return new object with one passed field
+ should return new object with a few passed field
+ should return an empty object if passed fields does not found
```
```diff
trimSymbols
+ should remove an identical consecutive characters that exceed the specified size
+ should return empty string if it was passed to function like an argument
+ should return empty string if "size" equal 0
+ should return the same string if "size" parameter wasn't specified
```
```diff
invertObj
+ should swap keys and values and return new object
+ should return empty object if was passed object without values
+ should return "undefined" if object wasn't passed
```
```diff
omit
+ should return a new object without passed field
+ should return a new object without few passed fields
+ should return initial object if passed fields doesn't found
```
```diff
uniq
+ should return array with uniq values
+ should return empty array if was passed array without values
+ should return empty array if arguments wasn't passed
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2020-11-09 12:16 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  const newAr = arr.slice();
good 👍

2020-11-09 12:17 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +    if (key in obj) {
помните мы говорили о том что не следует использовать `in` оператор для проверки наличия свойства в объекте. Напомните пожалуйста почему?

2020-11-09 12:17 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +    if (key in obj) {
аналогичный коммент по поводу `in`

2020-11-09 12:17 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +    return path.split('.').reduce((object, key) => {
было бы неплохо вынести `path.split('.')` в родительскую функцию, иначе данная операция будет выполняться каждый раз при вызове геттера, хотя данное значение требуется рассчитать только один раз при создании геттера

2020-11-09 12:17 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +  return (obj === undefined) ? undefined : Object.fromEntries(Object.entries(obj).map(([k, v]) => [v, k]));
такую запись для лучшей читабельности стоит разбить на несколько операций

2020-11-09 12:18 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/4-uniq/index.js
> +  let arReturn = [];
помните мы разбирали отличие `let` от `const`? Проверьте пожалуйста тут точно нужна `let`

2020-11-09 12:19 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/4-uniq/index.js
> +    arr.map(e => {
также обратите внимание вот на такую коллекцию данных https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Set

2020-11-09 12:19 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2020-11-10 09:13 UTC, facevoid63 commented on 02-javascript-data-types/2-pick/index.js
> +    if (key in obj) {
оператор in проверяет наличие ключа не только у объекта, но и у его родителя

2020-11-10 09:55 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-11-10 13:44 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +    const arPath = path.split('.');
было бы неплохо вынести `path.split('.')` в родительскую функцию, иначе данная операция будет выполняться каждый раз при вызове геттера, хотя данное значение требуется рассчитать только один раз при создании геттера

2020-11-10 13:44 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/4-uniq/index.js
> +  return Array.from(set);
Есть альтернативное решение:
```
return [...new Set(arr)];
```
подумайте в чем преимущества `Array.from`

2020-11-10 13:45 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +    return undefined;
здесь не следует явно возвращать `undefined`, достаточно просто:
```
if (obj === undefined) return;
```

2020-11-10 13:45 UTC, dosandk approved these changes
решения принимаются, посмотрите пожалуйста комментарии :mag:

2020-11-10 13:46 UTC, merged